apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chat-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5052
  selector:
    app: chat-service